myproject/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from . import views

# from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    re_path(r"^media/(?P<path>.*)$", serve, {"document_root": settings.MEDIA_ROOT}),
    re_path(r"^static/(?P<path>.*)$", serve, {"document_root": settings.STATIC_ROOT}),
    path("admin/", admin.site.urls),
    path("", views.homepage, name="home"),
    path("about/", views.about, name="about"),
    path("posts/", include("posts.urls")),
    path("users/", include("users.urls")),
]  # + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views

app_name = "posts"

urlpatterns = [
    path("", views.posts, name="list"),
    path("create/", views.create_post, name="create"),
    path("<slug:slug>", views.post_page, name="page"),
]

users/urls.py
from django.urls import path

from . import views

app_name = "users"

urlpatterns = [
    path("register/", views.handle_register, name="register"),
    path("login/", views.handle_login, name="login"),
    path("logout/", views.handle_logout, name="logout"),
]

posts/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Post(models.Model):
    title = models.CharField(max_length=255)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    body = models.TextField()
    slug = models.SlugField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    banner = models.ImageField(default="fallback.png", blank=True)

    def __str__(self) -> str:
        return self.title

users/models.py
from django.db import models

# Create your models here.

posts/forms.py
from django import forms
from . import models


class CreatePost(forms.ModelForm):
    class Meta:
        model = models.Post
        fields = ["title", "body", "slug", "banner"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs["class"] = "w-full p-2 text-darkest rounded"

myproject/views.py
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render


def homepage(request: HttpRequest) -> HttpResponse:
    # return HttpResponse("Hello, world. You're at the myproject index.")
    return render(request, "home.html")


def about(request: HttpRequest) -> HttpResponse:
    # return HttpResponse("About myproject.")
    return render(request, "about.html")

posts/views.py
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, redirect
from .models import Post
from django.contrib.auth.decorators import login_required
from . import forms


# Create your views here.
def posts(request: HttpRequest) -> HttpResponse:
    return render(
        request,
        "posts/posts_list.html",
        {
            "posts": Post.objects.all().order_by("created_at").reverse(),
        },
    )


def post_page(request: HttpRequest, slug: str) -> HttpResponse:
    return render(
        request,
        "posts/post_page.html",
        {
            "post": Post.objects.get(slug=slug),
        },
    )


@login_required(login_url="users:login")
def create_post(request: HttpRequest) -> HttpResponse:
    if request.method == "POST":
        form = forms.CreatePost(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect("posts:list")
    else:
        form = forms.CreatePost()
    print("FORM:", form)
    return render(
        request,
        "posts/create_post.html",
        {
            "form": form,
        },
    )

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
from django.http import HttpRequest, HttpResponse

# Create your views here.


def handle_register(request: HttpRequest) -> HttpResponse:
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            login(request, form.save())
            return redirect("posts:list")
        else:
            print(form.errors)
    else:
        form = UserCreationForm()
    return render(request, "users/register.html", {"form": form})


def handle_login(request: HttpRequest) -> HttpResponse:
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            login(request, form.get_user())
            if "next" in request.POST:
                return redirect(request.POST.get("next"))
            return redirect("posts:list")
        else:
            print(form.errors)
    else:
        form = AuthenticationForm()
    return render(request, "users/login.html", {"form": form})


def handle_logout(request: HttpRequest) -> HttpResponse:
    logout(request)
    return redirect("posts:list")

posts/templates/posts/create_post.html
{% extends "layout.html" %}
{% block title %}
    Create Post
{% endblock title %}
{% block content %}
    <div class="flex flex-col items-center w-full">
        <form action="{% url 'posts:create' %}"
              method="post"
              enctype="multipart/form-data"
              class="p-4 flex flex-col space-y-1 w-full [&_label]:text-secondary/70">
            {% csrf_token %}
            {{ form }}
            <button class="p-2 bg-secondary text-light rounded hover:bg-darkest transition">Create Post</button>
        </form>
    </div>
{% endblock content %}

posts/templates/posts/post_page.html
{% extends "layout.html" %}
{% block title %}
    {{ post.title }}
{% endblock title %}
{% block content %}
    <div class="w-full max-h-80 overflow-hidden rounded-lg">
        <img src="{{ post.banner.url }}"
             alt="{{ post.title }}"
             class="object-cover object-center w-full h-full max-h-80">
    </div>
    <div class="p-4">
        <h1 class="text-3xl font-bold uppercase tracking-widest">{{ post.title | title }}</h1>
        <h2 class="text-xl font-bold tracking-widest mt-2 italic">by {{ post.author | default:"Anonymous" | capfirst }}</h2>
        <p class="whitespace-pre-wrap">{{ post.body | linebreaksbr }}</p>
        <div class="flex justify-end">
            <a href="{% url 'posts:list' %}" class="hover:text-secondary">Back to posts</a>
        </div>
    </div>
{% endblock content %}

posts/templates/posts/posts_list.html
{% extends "layout.html" %}
{% block title %}
    Posts
{% endblock title %}
{% block content %}
    <div class="container mx-auto p-4">
        <div class="flex items-center justify-between">
            <h1 class="text-3xl font-bold uppercase tracking-widest">Posts</h1>
            <a href="{% url 'posts:create' %}"
               class="hover:text-secondary flex items-center{% if not user.is_authenticated %} cursor-default text-light/40 pointer-events-none{% endif %}">
                Create
                <span class="text-secondary text-2xl ml-2">+</span>
            </a>
        </div>
        {% for post in posts %}
            <article class="mt-4 p-4 bg-darkest rounded-lg shadow-md"
                     onclick="location.href='{% url 'posts:page' slug=post.slug %}'">
                <h2 class="text-xl font-bold">{{ post.title|title }} | {{ post.author | default:"Anonymous" | capfirst }}</h2>
                <i class="text-secondary">{{ post.slug }} | {{ post.created_at }}</i>
                <p>{{ post.body | truncatechars:200 }}</p>
            </article>
            {% comment %} <hr class="border-t-2 border-secondary"> {% endcomment %}
        {% endfor %}
    </div>
{% endblock content %}

templates/about.html
{% extends "layout.html" %}
{% block title %}
    About
{% endblock title %}
{% block content %}
    <h1>About</h1>
{% endblock content %}

templates/base_layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}My Django App{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <div class="navbar">
        <a href="{% url 'home' %}">Home</a>
        <a href="{% url 'about' %}">About</a>
    </div>
    <div style="margin-top: 50px;">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

templates/home.html
{% extends "layout.html" %}
{% block title %}
    Home
{% endblock title %}
{% block content %}
    <h1>Home</h1>
{% endblock content %}

templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="Django Blog Application">
        <meta name="keywords" content="django, blog">
        <title>
            {% block title %}
                My Django App
            {% endblock title %}
        </title>
        <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    </head>
    <body class="bg-darkest text-light">
        <nav class="bg-dark px-4 py-2">
            <ul class="flex justify-center space-x-10">
                <a href="{% url 'home' %}" class="hover:text-secondary">Home</a>
                <a href="{% url 'about' %}" class="hover:text-secondary">About</a>
                <a href="{% url 'posts:list' %}" class="hover:text-secondary">Posts</a>
                {% if user.is_anonymous %}
                    <a href="{% url 'users:register' %}" class="hover:text-secondary">Register</a>
                    <a href="{% url 'users:login' %}" class="hover:text-secondary">Login</a>
                {% endif %}
                {% if user.is_authenticated %}
                    <a href="{% url 'users:logout' %}" class="hover:text-secondary">Logout</a>
                {% endif %}
            </ul>
        </nav>
        <main class="container mx-auto p-4">
            <div class="bg-dark shadow-md rounded p-4">
                {% block content %}
                {% endblock content %}
            </div>
        </main>
    </body>
</html>

users/templates/users/login.html
{% extends "layout.html" %}
{% block title %}
    Login
{% endblock title %}
{% block content %}
    <h1>Login</h1>
    <form action="{% url "users:login" %}"
          method="post"
          class="flex flex-col [&_input]:my-2 [&_div]:flex [&_div]:justify-between [&_div]:w-80  [&_div]:mx-auto [&_div]:items-center [&_div]:space-x-2 [&_input]:w-full [&_input]:p-2 [&_input]:text-darkest [&_input]:rounded [&_.errorlist_li]:text-secondary [&_.errorlist]:text-xs [&_.errorlist]:text-center [&_.errorlist_li]:before:content-['*']">
        {% csrf_token %}
        {{ form }}
        {% if request.GET.next %}<input type="hidden" name="next" value="{{ request.GET.next }}">{% endif %}
        <div class="flex justify-end">
            <button type="submit"
                    class="p-2 bg-secondary text-light rounded hover:bg-darkest transition">Login</button>
        </div>
    </form>
{% endblock content %}

users/templates/users/register.html
{% extends "layout.html" %}
{% block title %}
    Register
{% endblock title %}
{% block content %}
    <h1>Register</h1>
    <form action="{% url "users:register" %}"
          method="post"
          class="flex flex-col [&_input]:my-2 [&_div]:flex [&_div]:justify-between [&_div]:w-80  [&_div]:mx-auto [&_div]:items-center [&_div]:space-x-2 [&_input]:w-full [&_input]:p-2 [&_input]:text-darkest [&_input]:rounded [&_.errorlist_li]:text-secondary [&_.errorlist]:text-xs [&_.errorlist]:text-center [&_.errorlist_li]:before:content-['*']">
        {% csrf_token %}
        {{ form }}
        <div class="flex justify-end">
            <button type="submit"
                    class="p-2 bg-secondary text-light rounded hover:bg-darkest transition">Register</button>
        </div>
    </form>
{% endblock content %}